stages:
  - deploy_primary_template
  - build_and_push_docker_image

deploy_primary_template:
  stage: deploy_primary_template
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws cloudformation deploy --template-file cloud_formation/ScanLingoPrimaryStack.json --stack-name ScanLingoPrimaryStack --no-fail-on-empty-changeset
    - aws cloudformation describe-stacks --stack-name ScanLingoPrimaryStack --query "Stacks[0].Outputs" > stack-outputs.json
    # Extract the values from the outputs and set them as environment variables
  artifacts:
    paths:
      - stack-outputs.json
  




build_and_push_docker_image:
  stage: build_and_push_docker_image
  image: ubuntu:latest
  variables:
    # Environment variables for AWS credentials
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  script:

    - apt-get update && apt-get install -y python3-pip unzip curl
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install
    - which aws
    - aws --version
    # -  docker run --rm -it amazon/aws-cli
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - echo "Creating environment file..."
    - ECR_REPO_URL=$(jq -r '.[] | select(.OutputKey=="ECRRepoURL") | .OutputValue' stack-outputs.json)
    # Create an environment file to store AWS credentials
    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
    - echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> .env
    - echo "AWS_REGION=$AWS_DEFAULT_REGION" >> .env
    - docker build -t scanlingo-core-backend:$CI_COMMIT_SHA -t scanlingo-core-backend:latest . --no-cache
    - docker tag scanlingo-core-backend:$CI_COMMIT_SHA $ECR_REPO_URL:latest
    - docker tag scanlingo-core-backend:$CI_COMMIT_SHA $ECR_REPO_URL:$CI_COMMIT_SHA
    - docker push $ECR_REPO_URL/scanlingo-core-backend:latest
    - docker push $ECR_REPO_URL/scanlingo-core-backend:$CI_COMMIT_SHA
  
