stages:
  - deploy_primary_template
  - build_and_push_docker_image

deploy_primary_template:
  stage: deploy_primary_template
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws cloudformation deploy --template-file cloud_formation/ScanLingoPrimaryStack.json --stack-name ScanLingoPrimaryStack --no-fail-on-empty-changeset
    - aws cloudformation describe-stacks --stack-name ScanLingoPrimaryStack --query "Stacks[0].Outputs" > stack-outputs.json
#     # Extract the values from the outputs and set them as environment variables
  artifacts:
    paths:
      - stack-outputs.json
  




build_and_push_docker_image:
  image: docker:20.10.16
  stage: build_and_push_docker_image
  services:
    - name: docker:20.10.16-dind
    # registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
      alias: docker
  variables:
    # Environment variables for AWS credentials
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
    DOCKER_HOST: tcp://docker:2375/
  # Environemt Variable for docker:dind service explaining to use overlay2 as supporting driver for docker
  # https://docs.docker.com/storage/storagedriver/overlayfs-driver/
    DOCKER_DRIVER: overlay2
    # We need to disable TLS (https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/#disable-tls)
    # to fix the error "docker: Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?"
    DOCKER_TLS_CERTDIR: ""
  script:

    - docker run --rm --entrypoint=sh -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"  -e "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" public.ecr.aws/aws-cli/aws-cli ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - echo "Creating environment file..."
    - ECR_REPO_URL=$(jq -r '.[] | select(.OutputKey=="ECRRepoURL") | .OutputValue' stack-outputs.json)
    # Create an environment file to store AWS credentials
    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
    - echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> .env
    - echo "AWS_REGION=$AWS_DEFAULT_REGION" >> .env
    - docker build -t scanlingo-core-backend:$CI_COMMIT_SHA -t scanlingo-core-backend:latest . --no-cache
    - docker tag scanlingo-core-backend:$CI_COMMIT_SHA $ECR_REPO_URL:latest
    - docker tag scanlingo-core-backend:$CI_COMMIT_SHA $ECR_REPO_URL:$CI_COMMIT_SHA
    - docker push $ECR_REPO_URL/scanlingo-core-backend:latest
    - docker push $ECR_REPO_URL/scanlingo-core-backend:$CI_COMMIT_SHA
  
