export AWS_ACCESS_KEY_ID=ASIAV3R3C7REKXNWPZYH
export AWS_SECRET_ACCESS_KEY=SfVS4A6hUBu3ZEFy8vuHIlKAYv8N0XTonwDkix75
export AWS_SESSION_TOKEN=FwoGZXIvYXdzEFoaDGwmMzyj4OOElO2hbCLAAcYa6oXgwVek4A1B6vjFgbdzBaZUL8TrbnomYSZ5d652h9ZgO+Y+UTYE0gYCcgNXXhykCNJWnG06vrcJy/tV/rYWbE/VH+XwtgaRLZi1krJ4wfW4TF7Qc8wxsARTuRVkSJyu9S1QI3jrGbaby3DhD0Z4FwWh7gP4rSqsCcZmEuHJGndS3rMP3/JoYlP/qxMvazlajdy8sdGzWw9xy8FssJm/YexYFcOfOWnwwGzuh/z2bk2uB8VVJZMp3HY4+svtqCi0v6amBjItb3h+GIWHxLG5Bc4aqfGm7laCIUmnmrS2bOzR0AIRQxw53q7yYHWTSCrnS+fQ
export AWS_DEFAULT_REGION=us-east-1
export AWS_ACCOUNT_ID=402777111624



aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
aws configure set aws_session_token $AWS_SESSION_TOKEN
aws configure set default.region $AWS_DEFAULT_REGION